= Netbewust Laden

The joint network operators expect that due to the rapidly increasing demand
for grid capacity on the low-voltage (LV) networks, congestion issues will
arise, and _Netbewust Laden_ is seen as one of the solutions.

This data product provides network operators with the opportunity to
periodically provide municipalities, charging station operators, _NAL_ regions,
and other stakeholders with uniform insights into which areas are expected to
experience (impending) capacity shortages.

This is to facilitate the mobility transition and to optimally utilize the
locally available grid capacity for all electricity users, preventing overload
caused by peaks in demand. The alternative is to reinforce the grid, which has
a long lead time, requires high investments, and will delay the energy
transition.

.Data Product
[d2,svg,theme=4]
----
grid-rows: 10
grid-columns: 6

horizontal-gap: 160
vertical-gap: 80

vars: {
  d2-config: {
    pad: 20
  }
}

1.class: empty
2.class: empty
cim\:ActivePowerLimit.class: grid
cim\:OperationalLimitSet.class: grid
cim\:Terminal_01: {
  class: grid
  label: "cim:Terminal"
}
cim\:Analog.class: grid

3.class: empty
4.class: empty
5.class: empty
6.class: empty
cim\:PowerTransformerEnd_01: {
  class: grid
  label: "cim:PowerTransformerEnd"
}
7.class: empty

ForecastDataSet.class: dataset
cim\:GeographicalRegion.class: enterprise
cim\:SubGeographicalRegion.class: enterprise
cim\:Substation.class: grid
cim\:PowerTransformer.class: grid
8.class: empty

9.class: empty
10.class: empty
11.class: empty
12.class: empty
cim\:PowerTransformerEnd_02: {
  class: grid
  label: "cim:PowerTransformerEnd"
}
13.class: empty

14.class: empty
15.class: empty
16.class: empty
17.class: empty
cim\:Terminal_02: {
  class: grid
  label: "cim:Terminal"
}
18.class: empty

19.class: empty
20.class: empty
21.class: empty
22.class: empty
cim\:TopologicalNode.class: grid
23.class: empty

24.class: empty
cim\:MarketParticipant.class: market
cim\:RegisteredLoad.class: market
cim\:MktConnectivityNode.class: market
cim\:Terminal_03: {
  class: grid
  label: "cim:Terminal"
}
25.class: empty

26.class: empty
cim\:MarketRole.class: market
27.class: empty
cim\:UsagePoint.class: enterprise
cim\:EnergyConsumer.class: grid
cim\:Location.class: enterprise

ForecastDataSet -> cim\:GeographicalRegion: "geographical_regions"
cim\:GeographicalRegion -> cim\:SubGeographicalRegion: "regions"
cim\:SubGeographicalRegion -> cim\:Substation: "substations"
cim\:Substation -> cim\:PowerTransformer: "equipments"
cim\:PowerTransformer -> cim\:PowerTransformerEnd_01: "power_transformer_end"
cim\:PowerTransformerEnd_01 -> cim\:Terminal_01: "terminal"
cim\:Terminal_01 -> cim\:OperationalLimitSet: "operational_limit_set"
cim\:Terminal_01 -> cim\:Analog: "measurements"
cim\:OperationalLimitSet -> cim\:ActivePowerLimit: "operational_limit"
cim\:PowerTransformerEnd_02 -> cim\:Terminal_02: "terminal"
cim\:Terminal_02 -> cim\:TopologicalNode: "topological_nodes"
cim\:PowerTransformer -> cim\:PowerTransformerEnd_02: "power_transformer_end"
cim\:TopologicalNode -> cim\:Terminal_03: "terminal"
cim\:Terminal_03 -> cim\:EnergyConsumer: "conducting_equipment"
cim\:EnergyConsumer -> cim\:Location: "location"
cim\:EnergyConsumer -> cim\:UsagePoint: "usage_points"
cim\:Terminal_03 -> cim\:MktConnectivityNode: "connectivity_node"
cim\:MktConnectivityNode -> cim\:RegisteredLoad: "registered_resource"
cim\:RegisteredLoad -> cim\:MarketParticipant: "market_participant"
cim\:MarketParticipant -> cim\:MarketRole: "market_roles"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
  dataset: {
    style: {
      shadow: true
    }
  }
}
----

== Additional schemas

* xref:schema:attachment$schemas/json_schema/dp_netbewust_laden.json_schema.json[JSON schema]
* xref:schema:attachment$examples/dp_netbewust_laden.example.json[Example JSON instance data]
