= Netbewust Laden

The joint network operators expect that due to the rapidly increasing demand
for grid capacity on the low-voltage (LV) networks, congestion issues will
arise, and _Netbewust Laden_ is seen as one of the solutions.

This data product provides network operators with the opportunity to
periodically provide municipalities, charging station operators, _NAL_ regions,
and other stakeholders with uniform insights into which areas are expected to
experience (impending) capacity shortages.

This is to facilitate the mobility transition and to optimally utilize the
locally available grid capacity for all electricity users, preventing overload
caused by peaks in demand. The alternative is to reinforce the grid, which has
a long lead time, requires high investments, and will delay the energy
transition.

.Data Product
[d2,svg,theme=4]
----
grid-rows: 10
grid-columns: 6

horizontal-gap: 160
vertical-gap: 160

vars: {
  d2-config: {
    pad: 20
  }
}

1.class: empty
2.class: empty
cim\:ActivePowerLimit.class: grid
cim\:OperationalLimitSet.class: grid
cim\:PowerTransformerEnd_01: {
  class: grid
  label: "cim:PowerTransformerEnd"
}
cim\:Analog.class: grid

ForecastDataSet.class: dataset
cim\:GeographicalRegion.class: enterprise
cim\:SubGeographicalRegion.class: enterprise
cim\:Substation.class: grid
cim\:PowerTransformer.class: grid
3.class: empty

4.class: empty
5.class: empty
6.class: empty
cim\:Location_02: {
    class: enterprise
    label: "cim:Location"
}
cim\:PowerTransformerEnd_02: {
  class: grid
  label: "cim:PowerTransformerEnd"
}
cim\:BaseVoltage.class: grid

9.class: empty
cim\:MarketParticipant.class: market
cim\:RegisteredLoad.class: market
cim\:MktConnectivityNode: {
  class: market
}
cim\:TopologicalNode: {
  class: grid
}
10.class: empty

11.class: empty
cim\:MarketRole.class: market
12.class: empty
cim\:UsagePoint.class: enterprise
cim\:EnergyConsumer.class: grid
cim\:Location.class: enterprise

ForecastDataSet -> cim\:GeographicalRegion: "geographical_regions"
cim\:GeographicalRegion -> cim\:SubGeographicalRegion: "regions"
cim\:SubGeographicalRegion -> cim\:Substation: "substations"
cim\:Substation -> cim\:PowerTransformer: "equipments"
cim\:Substation -> cim\:Location_02: "location"
cim\:PowerTransformer -> cim\:PowerTransformerEnd_01: "power_transformer_end"
cim\:PowerTransformerEnd_01 <-> cim\:OperationalLimitSet: {
  label: "operational_\nlimit_set"
  source-arrowhead.shape: circle
}
cim\:PowerTransformerEnd_01 <-> cim\:Analog: {
  label: "measurements"
  source-arrowhead.shape: circle
}
cim\:OperationalLimitSet -> cim\:ActivePowerLimit: "operational_limit"
cim\:PowerTransformerEnd_02 -> cim\:BaseVoltage: "base_voltage"
cim\:PowerTransformerEnd_02 <-> cim\:TopologicalNode: {
  label: "topological_nodes"
  source-arrowhead.shape: circle
}
cim\:PowerTransformer -> cim\:PowerTransformerEnd_02: "power_transformer_end"
cim\:TopologicalNode <-> cim\:EnergyConsumer: {
  label: "conducting_equipment"
  source-arrowhead.shape: circle
}
cim\:EnergyConsumer -> cim\:Location: "location"
cim\:EnergyConsumer -> cim\:UsagePoint: "usage_points"
cim\:TopologicalNode <-> cim\:MktConnectivityNode: {
  label: "connectivity_node"
  source-arrowhead.shape: circle
}
cim\:MktConnectivityNode -> cim\:RegisteredLoad: "registered_resource"
cim\:RegisteredLoad -> cim\:MarketParticipant: "market_participant"
cim\:MarketParticipant -> cim\:MarketRole: "market_roles"

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
  dataset: {
    style: {
      shadow: true
    }
  }
}
----

Future versions will include the following additions:

* BaseVoltage becomes required for outgoing PowerTransformer;
* OperationalLimitSet and Analog move to outgoing PowerTransformerEnd;
* Substations in multiple parts of the grid (MV/LV) are supported through the
use of BaseVoltage. Associate the cluster of charge points through the
TopologicalNode to multiple outgoing PowerTransformerEnds;
* EnergyConsumer.location moves to UsagePoint.location, to allow UsagePoints to
have a separate Location for a single EnergyConsumer. This is required for
large scale EnergyConsumers, such as airports and football arenas.

== Additional schemas

* xref:schema:attachment$schemas/json_schema/dp_netbewust_laden.json_schema.json[JSON schema]
* xref:schema:attachment$examples/dp_netbewust_laden.example.json[Example JSON instance data]
